### ISSUE TITLE
Some instructions missing?

### ISSUE THREAD

**Issue by tsg21** [Distelli/graphql-apigen#11]
Perhaps I am missing something obvious, but would you mind adding instructions explaining what needs to happen to trigger the generation of the interface source?

I can see it's some Maven plugin-fu, but I haven't managed to figure out exactly what I need to do.

**Comment by brimworks** [comment]
Thanks for asking! I'll post something soon.

**Comment by brimworks** [comment]
I've posted this:

https://github.com/Distelli/graphql-apigen#getting-started

If that isn't helpful, please let me know what your getting stuck on (perhaps giving me a link to your maven project?).

Thanks,
-Brian

**Comment by tsg21** [comment]
That's helped, thanks. I'm using Eclipse and m2e and also had to add some pluginmanagment stuff to stop it complaining.

Anyway - I now have working generated sources. I'll go back to playing. Many thanks.

**Comment by brimworks** [comment]
Excellent, I'll close this issue then.
