### ISSUE TITLE
Hello world example

### ISSUE THREAD

**Issue by marcelalburg** [Distelli/graphql-apigen#15]
Hello,

it is possible to provide a simple helloWorld example. i try to use your code but it's not working.

my schema file 

```
type helloWorldQuery {
	hello: String!
}

```
and my GuiceBinder

```
public class Binder extends AbstractModule {
	@Override
	protected void configure() {
		install(new GraphQLModule());

		bind(helloWorldQuery.class).toInstance(new helloWorldQueryImpl());
        }

	class helloWorldQueryImpl implements helloWorldQuery {
		public String getHello() {
			return "world";
		}
	}
}
```

But the result for the query:

`{"query":"{hello}"}
`
is always:

`{"data":{"hello":null}}
`

How it is possible to define a DataFetcher ?

Something like this:

```
DataFetcher dataFetcher = new DataFetcher() {

			@Override
			public Object get(DataFetchingEnvironment environment) {
				return "World";
			}
		};
```

Thanks

Marcel

**Comment by brimworks** [comment]
What code are you using to build the `GraphQLSchema` object? In the "Post" example, this is the code I'm asking about:

```java
        private GraphQL graphQL;
        @Inject
        protected void init(Map<String, GraphQLType> types) {
            GraphQLSchema schema = GraphQLSchema.newSchema()
                .query((GraphQLObjectType)types.get("QueryPosts"))
                .mutation((GraphQLObjectType)types.get("MutatePosts"))
                .build(new HashSet<>(types.values()));
            graphQL = new GraphQL(schema, new BatchedExecutionStrategy());
        }
        public String execute(String query) {
            ExecutionResult result = graphQL.execute(query);
            return OM.writeValueAsString(result);
        }
```

**Comment by brimworks** [comment]
Note that graphql-apigen implements the DataFetchers for you. Specifically, when you wire your helloWorldQuery class to be implemented with helloWorldQueryImpl, your saying that helloWorldQueryImpl will be your "data fetcher". You can also implement "resolvers" so you can implement recursive queries. Specifically, instead of returning a "full" subtype, you return an "unresolved" subtype which just has the id field set. In your resolver, you take as input the "unresolved" subtype and return "full" subtypes.

**Comment by marcelalburg** [comment]
Hello,

thanks for your fast answer.

I implemented the Schema like in your examples


```
	@Inject
	Map<String, GraphQLType> types;

        ... 

GraphQLSchema schema = GraphQLSchema.newSchema().query((GraphQLObjectType) types.get("helloWorldQuery")).build(new HashSet<>(types.values()));

		GraphQL graphQL = GraphQL.newGraphQL(schema).build();

		Map<String, Object> variables = queryQL.getJsonObject("variables", new JsonObject()).getMap();

        .....

			ExecutionResult executionResult = graphQL.execute(queryQL.getString("query"), null, null, variables);
```

**Comment by brimworks** [comment]
If you can post your hello world example on github I can take a look at it this weekend.

Thanks,
-Brian

**Comment by marcelalburg** [comment]
Hi,

thanks for take a look

https://github.com/marcelalburg/vertx_graphql_hello_world_example

you can run the com.example.runner.Runner class to start the project.


my expectation is, that Guice is loading my helloWorldQueryImpl (defined in com.example.guice.Binder) and use the getHello function as DataFetcher

so my expected output should be


```
curl localhost:8082/graphql

{hello=World}
```

Thanks
Marcel

**Comment by brimworks** [comment]
I found the problems:

https://github.com/marcelalburg/vertx_graphql_hello_world_example/pull/1

Some of them are issues with apigen (forgot to define .dataFetcher if id field is not present), and I need to update apigen to make it work with the latest graphql-java.

Thanks,
-Brian

**Comment by brimworks** [comment]
The dataFetcher is now defined even if the id field is not present:

https://github.com/Distelli/graphql-apigen/commit/0e1064848aab41ee6645c09d06a61a23a0b3b698

Thanks,
-Brian

**Comment by marcelalburg** [comment]
Hi, thanks. I tried it locally and the generated files contains the datafetcher now. But it's not loading my custom resolver. the property _imp is not bind by guice :/

**Comment by marcelalburg** [comment]
Hello gain,

i found why it's not working. I understand the Resolver wrong. If i implement and bind the interface helloWorldQuery to something like this:

```
public class HelloWorldQuery implements helloWorldQuery {
	@Override
	public String getHello() {
		return "World";
	}
	
	@Override
	public String getId() {
		return "123";
	}
}
```

then it works.

Thanks for your help.

Marcel
