### ISSUE TITLE
Update to the new graphql-java Version

### ISSUE THREAD

**Issue by marcelalburg** [Distelli/graphql-apigen#16]
Hello,

can you update to the latest graphql-java version: 2.4.0 

Thanks a lot
Marcel

**Comment by brimworks** [comment]
Released as version 2.2.0, note that the sonatype repository sometimes takes a little while to sync.

Thanks to @ieugen for the pull request!

**Comment by ieugen** [comment]
Great :). Thank you. By the way, graphql-java releases nightly builds. I think we could have a develop branch that can track the un-released version of graphql-java so we can release just as soon as they make a release. 

We need to add the repository [1] and we can track it easily. 

[1] https://github.com/graphql-java/graphql-java#how-to-use-the-latest-build-with-maven
