### ISSUE TITLE
The `graphql-apigen-pom` doesn't seem to be in maven central

### ISSUE THREAD

**Issue by ryangardner** [Distelli/graphql-apigen#3]
I tried configuring the plugin like this: 

```
           <plugin>
                <groupId>com.distelli.graphql</groupId>
                <artifactId>graphql-apigen</artifactId>
                <version>1.1.0</version>
                <executions>
                    <execution>
                        <id>generate-grapqhl-interfaces</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>apigen</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/graphql</sourceDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

but when I execute I get an error that it can't find the parent pom: 

```[ERROR] Plugin com.distelli.graphql:graphql-apigen:1.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.distelli.graphql:graphql-apigen:jar:1.1.0: Could not find artifact com.distelli.graphql:graphql-apigen-pom:pom:1.1.0```

For what it's worth, I haven't been able to find it when I've looked for it manually on maven central either

**Comment by brimworks** [comment]
Thanks for pointing this out. I'll investigate why the parent pom was not published...

**Comment by brimworks** [comment]
Okay, version 1.1.1 has been published, but due to maven central syncing delay, you might need to do this in the short term:

```xml
  <distributionManagement>
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
    </repository>
  </distributionManagement>
```

**Comment by devinsba** [comment]
Looks good now, sync has finished
