### ISSUE TITLE
Possibly search for .graphqls files in addition to .graphql files?

### ISSUE THREAD

**Issue by apottere** [Distelli/graphql-apigen#6]
According to the Intellij plugin, graphql schemas should be [defined in .graphqls files, not .graphql](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/27a996aef00ea18baf137d6ce850db035a922ab7/src/main/com/intellij/lang/jsgraphql/ide/annotator/JSGraphQLLanguageWarningAnnotator.java#L32).  I haven't been able to find any substantial sources to back this up besides a few hits on google, including the readme [here](https://github.com/nknapp/gql2ts-for-server#usage).

Would it be a good idea to glob for *both* `.graphql` and `.graphqls` files in `ApiGenMojo`?

**Comment by apottere** [comment]
For context, right now we have both a `.graphqls` file (for intellij plugin support, and a link to that file named `.graphql` for codegen - we'd like to reduce this to one file.

**Comment by brimworks** [comment]
Sounds good to me, it should be a simple change.

**Comment by brimworks** [comment]
Sorry for the neglect on this issue. I plan to add support for this in about a week.

**Comment by brimworks** [comment]
Released in version 2.1.0 :).

**Comment by apottere** [comment]
Thanks!
